// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VnsProjectTrips.Data;

namespace VnsProjectTrips.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20220617145650_createModelsMarkets")]
    partial class createModelsMarkets
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("VnsProjectTrips.Domain.Models.Market", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("About")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Category")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeliveryEstimate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Hours")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Rating")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Markets");
                });

            modelBuilder.Entity("VnsProjectTrips.Domain.Models.MarketItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MarketId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("OrderId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("MarketId");

                    b.HasIndex("OrderId");

                    b.ToTable("MarketItens");
                });

            modelBuilder.Entity("VnsProjectTrips.Domain.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.Property<string>("OptionalAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaymentOption")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("VnsProjectTrips.Domain.Models.OrderMarket", b =>
                {
                    b.Property<int>("MarketId")
                        .HasColumnType("int");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.HasKey("MarketId", "OrderId");

                    b.HasIndex("OrderId");

                    b.ToTable("OrdersMarkets");
                });

            modelBuilder.Entity("VnsProjectTrips.Domain.Models.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime?>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int?>("MarketId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("comments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("rating")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("MarketId");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("VnsProjectTrips.Domain.Models.MarketItem", b =>
                {
                    b.HasOne("VnsProjectTrips.Domain.Models.Market", "Market")
                        .WithMany("MarketItens")
                        .HasForeignKey("MarketId");

                    b.HasOne("VnsProjectTrips.Domain.Models.Order", "Order")
                        .WithMany("MarketItens")
                        .HasForeignKey("OrderId");

                    b.Navigation("Market");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("VnsProjectTrips.Domain.Models.OrderMarket", b =>
                {
                    b.HasOne("VnsProjectTrips.Domain.Models.Market", "Market")
                        .WithMany("OrdersMarkets")
                        .HasForeignKey("MarketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VnsProjectTrips.Domain.Models.Order", "Order")
                        .WithMany("OrdersMarkets")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Market");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("VnsProjectTrips.Domain.Models.Review", b =>
                {
                    b.HasOne("VnsProjectTrips.Domain.Models.Market", "Market")
                        .WithMany("Reviews")
                        .HasForeignKey("MarketId");

                    b.Navigation("Market");
                });

            modelBuilder.Entity("VnsProjectTrips.Domain.Models.Market", b =>
                {
                    b.Navigation("MarketItens");

                    b.Navigation("OrdersMarkets");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("VnsProjectTrips.Domain.Models.Order", b =>
                {
                    b.Navigation("MarketItens");

                    b.Navigation("OrdersMarkets");
                });
#pragma warning restore 612, 618
        }
    }
}
